export const MODES = {
  STABLE: "STABLE",
  ELEVATED: "ELEVATED",
  CRITICAL: "CRITICAL",
  LOCKDOWN: "LOCKDOWN",
  RECOVERY: "RECOVERY",
};

export const RISK_THRESHOLDS = {
  ELEVATED: 40,
  CRITICAL: 75,
  LOCKDOWN: 90,
};

export const SYSTEM_LIMITS = {
  MAX_ATTACK_HISTORY: 500,
  CLUSTER_MIN_COUNT: 3,
  ESCALATION_MIN_HIGH: 3,
  ESCALATION_WINDOW: 5,
};

export const RENDER_CONFIG = {
  GLOBE_RADIUS: 2,
  ARC_HEIGHT_FACTOR: 0.5,
  SHOCKWAVE_SPEED: 0.01,
  RADAR_SPEED: 0.02,
  SHIELD_OPACITY: 0.3,
};

export const LATENCY_CONFIG = {
  PING_INTERVAL: 5000,
};